import streamlit as st
import pandas as pd
import requests

# ---------- LOGIN STATE ----------
if "logged_in" not in st.session_state:
    st.session_state.logged_in = False

if "user_id" not in st.session_state:
    st.session_state.user_id = ""
# -------- BACKEND API CALL --------

API_URL = "http://127.0.0.1:8000/risk"

try:
    response = requests.get(API_URL, timeout=5)
    backend_data = response.json()
except:
    backend_data = {
        "risk_level": "Moderate",
        "confidence": "Medium",
        "explanation": "Backend not reachable. Showing fallback data."
    }

risk_level = backend_data["risk_level"]
confidence = backend_data["confidence"]
explanation = backend_data["explanation"]



# Backend configuration
BACKEND_URL = "https://YOUR-BACKEND-URL"
USER_ID = "demo_user"


# Page setup
st.set_page_config(page_title="WellSense", layout="wide")

def login_screen():
    st.title("🔐 Welcome to WellSense")
    st.write("Please enter your name to continue")

    username = st.text_input("Your Name")

    if st.button("Login"):
        if username.strip():
            st.session_state.logged_in = True
            st.session_state.user_id = username.strip()
            st.rerun()
        else:
            st.error("Please enter a valid name")

if not st.session_state.logged_in:
    login_screen()
    st.stop()
    
# Welcome message
st.markdown(f"## 👋 Welcome **{st.session_state.user_id}**!")



# Header
st.title("🧠 WellSense")
st.caption("A non-clinical well-being awareness tool")
st.info("WellSense helps you reflect on routine changes over time.")


st.divider()

# Layout
left, right = st.columns([2, 1])

with left:
    st.subheader("📊 Behaviour Trends")

    st.markdown("### Enter your recent routine consistency")

    sleep_consistency = st.slider(
        "😴 Sleep Consistency",
        min_value=0,
        max_value=100,
        value=75
    )

    activity_consistency = st.slider(
        "🏃 Activity Consistency",
        min_value=0,
        max_value=100,
        value=65
    )

    routine_stability = st.slider(
        "📅 Routine Stability",
        min_value=0,
        max_value=100,
        value=70
    )

    input_data = pd.DataFrame({
        "Metric": [
            "Sleep Consistency",
            "Activity Consistency",
            "Routine Stability"
        ],
        "Score": [
            sleep_consistency,
            activity_consistency,
            routine_stability
        ]
    })

    st.bar_chart(input_data.set_index("Metric"))
average_score = (
    sleep_consistency +
    activity_consistency +
    routine_stability
) / 3
if average_score >= 70:
    dynamic_confidence = "High"
elif average_score >= 40:
    dynamic_confidence = "Medium"
else:
    dynamic_confidence = "Low"


with right:
    st.subheader("🚦 Well-Being Indicator")

    if risk_level == "Low":
        st.success("Low change from your usual routine")
    elif risk_level == "Moderate":
        st.warning("Moderate change from your usual routine")
    else:
        st.error("Higher change from your usual routine")

    st.caption(f"Confidence level: {dynamic_confidence}")




st.subheader("🧠 Why am I seeing this?")

st.write(
    "Over the past week, your routine consistency has shown more variation "
    "than usual. This comparison is made against your own recent patterns, "
    "not against other users."
)



st.divider()

# Explanation
st.info(
    "The indicator reflects how recent routine patterns compare to your "
    "personal baseline. Temporary changes may be caused by travel, workload, "
    "or schedule shifts. This insight is awareness-focused and non-clinical."
)


# User controls
st.subheader("🔐 Your Controls")

st.checkbox("I understand this is a non-clinical tool")

if st.button("⏸ Pause Monitoring"):
    st.warning("Monitoring paused.")

if st.button("🗑 Delete My Data"):
    st.error("Your data has been removed.")

st.markdown("---")
st.caption(
    "⚠️ This tool does not provide medical advice, diagnosis, or treatment."
)

st.subheader("🔍 How this works")
st.write("""
WellSense compares recent behavioral signals against your personal baseline.
The risk indicator is generated by a backend model and is awareness-focused,
not diagnostic.
""")

st.subheader("⚖️ Ethics & Privacy")
st.write("""
• No medical diagnosis is provided  
• No personal identity is stored  
• Insights are user-controlled and explainable
""")

st.markdown("---")
st.caption("Built with Streamlit • FastAPI • Explainable ML")
